message:  # Customize the comment made by the bot
    opened:  # Messages when a new PR is submitted
        header: "Hello @{name}! Thank you for submitting this pull-request!"
                # The keyword {name} is converted into the author's username
        footer: "Do you know about the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)?"
                # The messages can be written as they would over GitHub
    updated:  # Messages when new commits are added to the PR
        header: "Hello @{name}! Thanks for updating the PR!"
        footer: ""  # Why to comment the link to the style guide everytime? :)
    no_errors: "Cheers! There are no PEP8 issues in this pull-request. :beers: "
