#!/bin/bash

source /usr/local/bin/virtualenvwrapper.sh

workon oggm_env

pip install --quiet --upgrade pip

echo "Installing numpy..."
pip install --quiet numpy

echo "Installing scipy..."
pip install --quiet scipy

echo "Installing pandas shapely matplotlib..."
pip install --quiet pandas shapely
pip install --quiet matplotlib

echo "Installing gdal fiona..."
pip install --quiet gdal==1.10.0 --install-option="build_ext" --install-option="--include-dirs=/usr/include/gdal"
pip install --quiet fiona --install-option="build_ext" --install-option="--include-dirs=/usr/include/gdal"

echo "Installing other packages..."
pip install --quiet pyproj rasterio Pillow geopandas netcdf4 scikit-image configobj joblib xarray nose

echo "Installing git packages..."
pip install --quiet git+https://github.com/fmaussion/motionless.git
pip install --quiet git+https://github.com/fmaussion/salem.git
pip install --quiet git+https://github.com/fmaussion/cleo.git

deactivate
echo "Done installing pip packages"